name: PR

on:
  pull_request:
    types: [edited, opened, reopened, synchronize]

jobs:
  title:
    runs-on: ubuntu-latest

    name: Check PR title

    steps:
      - name: Checkout
        uses: actions/checkout@v7

      - name: Set up pixi
        uses: prefix-dev/setup-pixi@v0.10.1
        with:
          environments: dev

      - name: Check PR title
        run: |
          pixi run -e dev cz check --message "${{ github.event.pull_request.title }}"
