name: Test

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest

    name: Lint

    steps:
      - name: Checkout
        uses: actions/checkout@v7

      - name: Set up pixi
        uses: prefix-dev/setup-pixi@v0.10.1
        with:
          environments: dev

      - name: Lint app
        run: pixi run -e dev lint

  test:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        environment: [py310, py311, py312, py313, py314]

    name: ${{ matrix.environment }}

    steps:
      - name: Checkout
        uses: actions/checkout@v7

      - name: Set up pixi
        uses: prefix-dev/setup-pixi@v0.10.1
        with:
          environments: ${{ matrix.environment }}

      - name: Test app
        run: pixi run -e ${{ matrix.environment }} test
